version: '3.7'

services:
  jupyter:
    build: .
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    container_name: jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    networks:
      cassandra-network:
        ipv4_address: 172.18.0.5

  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_SEEDS: "cassandra-node1"
      CASSANDRA_START_RPC: "true"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    networks:
      cassandra-network:
        ipv4_address: 172.18.0.2

networks:
  cassandra-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
